services:
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: turismo_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "1234:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "--password="]
      interval: 10s
      retries: 0
      start_period: 30s

  app:
    build: .
    container_name: app
    ports:
      - "9999:9999"
      - "9001:9001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/turismo_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 

volumes:
  db-data:
